# Generated by Django 2.0.3 on 2018-05-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarDB', '0002_auto_20180528_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseproperty',
            name='BIRcgt',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='BIRdst',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='LGUtransfer',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='OTHERSnotorial',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='RODit',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='RODlra',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='SUMother',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='TAXother',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='balance',
            field=models.FloatField(default=None),
        ),
    ]
