# Generated by Django 2.0.3 on 2018-05-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarDB', '0003_auto_20180528_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=255)),
                ('barangay', models.CharField(max_length=255)),
                ('regLandOwner', models.CharField(max_length=255)),
                ('contactNum', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('representative', models.CharField(max_length=255)),
                ('titleNum', models.CharField(max_length=255)),
                ('lotNum', models.CharField(max_length=255)),
                ('areaHectares', models.FloatField(default=None)),
                ('surveyNum', models.CharField(max_length=255)),
                ('pricePerHectare', models.FloatField(default=None)),
                ('totalContractPrice', models.FloatField(default=None)),
                ('firstPayAmount', models.FloatField(default=None)),
                ('firstPayDate', models.DateField(default=None)),
                ('secPayAmount', models.FloatField(default=None)),
                ('secPayDate', models.DateField(default=None)),
                ('thirdPayAmount', models.FloatField(default=None)),
                ('thirdPayDate', models.DateField(default=None)),
                ('fourthPayAmount', models.FloatField(default=None)),
                ('fourthPayDate', models.DateField(default=None)),
                ('fifthPayAmount', models.FloatField(default=None)),
                ('fifthPayDate', models.DateField(default=None)),
                ('sixthPayAmount', models.FloatField(default=None)),
                ('sixthPayDate', models.DateField(default=None)),
                ('seventhPayAmount', models.FloatField(default=None)),
                ('seventhPayDate', models.DateField(default=None)),
                ('eigthPayAmount', models.FloatField(default=None)),
                ('eigthPayDate', models.DateField(default=None)),
                ('ninthPayAmount', models.FloatField(default=None)),
                ('ninthPayDate', models.DateField(default=None)),
                ('tenthPayAmount', models.FloatField(default=None)),
                ('tenthPayDate', models.DateField(default=None)),
                ('releasedPayment', models.FloatField(default=None)),
                ('balance', models.FloatField(default=None)),
                ('BIRcgt', models.FloatField(default=None)),
                ('BIRdst', models.FloatField(default=None)),
                ('LGUtransfer', models.FloatField(default=None)),
                ('RODlra', models.FloatField(default=None)),
                ('RODit', models.FloatField(default=None)),
                ('OTHERSnotorial', models.FloatField(default=None)),
                ('SUMother', models.FloatField(default=None)),
                ('TAXother', models.FloatField(default=None)),
                ('Payee', models.CharField(max_length=255)),
                ('area', models.FloatField(default=None)),
            ],
        ),
        migrations.RenameField(
            model_name='leaseproperty',
            old_name='eigthPayDate',
            new_name='dateRelease',
        ),
        migrations.RenameField(
            model_name='leaseproperty',
            old_name='lotNum',
            new_name='taxDec',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='areaHectares',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='eigthPayAmount',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='fifthPayAmount',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='fifthPayDate',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='firstPayAmount',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='firstPayDate',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='fourthPayAmount',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='fourthPayDate',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='ninthPayAmount',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='ninthPayDate',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='releasedPayment',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='secPayAmount',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='secPayDate',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='seventhPayAmount',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='seventhPayDate',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='sixthPayAmount',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='sixthPayDate',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='surveyNum',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='tenthPayAmount',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='tenthPayDate',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='thirdPayAmount',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='thirdPayDate',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='titleNum',
        ),
    ]
