# Generated by Django 2.0.3 on 2018-05-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarDB', '0004_auto_20180528_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('accountType', models.IntegerField(choices=[(0, 'Regular User'), (1, 'Admin')], default=0)),
            ],
        ),
    ]
