# Generated by Django 2.0.3 on 2018-05-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SolarDB', '0007_auto_20180530_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='emailAdd',
        ),
    ]
