# Generated by Django 2.0.3 on 2018-05-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarDB', '0008_auto_20180530_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emailAdd',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
