# Generated by Django 2.0.3 on 2018-05-30 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SolarDB', '0009_auto_20180530_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='emailAdd',
        ),
    ]
