# Generated by Django 2.0.3 on 2018-06-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarDB', '0010_remove_user_emailadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesproperty',
            name='eigthPayAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='fifthPayAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='fourthPayAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='ninthPayAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='secPayAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='seventhPayAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='sixthPayAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='tenthPayAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='thirdPayAmount',
            field=models.FloatField(default=0),
        ),
    ]
