# Generated by Django 2.0.3 on 2018-06-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarDB', '0011_auto_20180606_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseproperty',
            name='advPayment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='balance',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='lotNum',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='titleNum',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year10Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year10Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year11Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year11Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year12Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year12Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year13Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year13Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year14Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year14Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year15Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year15Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year16Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year16Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year17Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year17Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year18Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year18Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year19Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year19Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year20Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year20Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year21Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year21Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year22Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year22Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year23Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year23Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year24Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year24Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year25Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year25Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year26Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year26Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year27Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year27Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year28Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year28Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year29Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year29Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year2Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year2Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year30Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year30Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year3Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year3Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year4Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year4Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year5Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year5Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year6Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year6Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year7Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year7Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year8Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year8Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year9Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year9Pay',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='leaseproperty',
            name='Address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='leaseproperty',
            name='Payee',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='leaseproperty',
            name='barangay',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='leaseproperty',
            name='contactNum',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='leaseproperty',
            name='municipality',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='leaseproperty',
            name='province',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='leaseproperty',
            name='regLandOwner',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='leaseproperty',
            name='region',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='leaseproperty',
            name='representative',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='leaseproperty',
            name='taxDec',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='Address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='Payee',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='barangay',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='contactNum',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='eigthPayDate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='fifthPayDate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='firstPayDate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='fourthPayDate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='lotNum',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='municipality',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='ninthPayDate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='province',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='regLandOwner',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='region',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='representative',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='secPayDate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='seventhPayDate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='sixthPayDate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='surveyNum',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='tenthPayDate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='thirdPayDate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesproperty',
            name='titleNum',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
