# Generated by Django 2.0.5 on 2018-06-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarDB', '0012_auto_20180606_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseproperty',
            name='year1Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='year1Pay',
            field=models.FloatField(default=0),
        ),
    ]
