# Generated by Django 2.0.5 on 2018-06-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarDB', '0013_auto_20180606_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseproperty',
            name='numofyear',
            field=models.FloatField(default=None),
        ),
    ]
