# Generated by Django 2.0.5 on 2018-06-13 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SolarDB', '0015_auto_20180608_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesproperty',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='salesproperty',
            name='lotNum',
        ),
        migrations.RemoveField(
            model_name='salesproperty',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='salesproperty',
            name='surveyNum',
        ),
    ]
