# Generated by Django 2.0.5 on 2018-06-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarDB', '0016_auto_20180613_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseproperty',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='totalContractPrice',
        ),
        migrations.AlterField(
            model_name='leaseproperty',
            name='advPaymentDate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='leaseproperty',
            name='numofyear',
            field=models.CharField(default='', max_length=255),
        ),
    ]
