# Generated by Django 2.0.5 on 2018-06-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarDB', '0018_auto_20180613_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseproperty',
            name='SUMother',
        ),
        migrations.RemoveField(
            model_name='leaseproperty',
            name='TAXother',
        ),
        migrations.AddField(
            model_name='leaseproperty',
            name='yeartotal',
            field=models.FloatField(default=0),
        ),
    ]
