# Generated by Django 2.0.5 on 2018-06-13 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SolarDB', '0019_auto_20180613_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseproperty',
            name='dateRelease',
        ),
    ]
